# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-08 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190308_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.IntegerField(default=0)),
                ('likes_count', models.IntegerField(default=0)),
                ('last_viewed', models.DateField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Blog',
            new_name='Story',
        ),
        migrations.AddField(
            model_name='storymetadata',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Story'),
        ),
    ]
